name: pogema-debug

global_settings:
  use_wandb: False
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 2000000
async_ppo:
  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 4096
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 12
  num_envs_per_worker: 8
environment:
  name: Pogema-8x8-easy-v0
