algo: 
  grid_search: [ QMIX, VDN, IQL, ]
settings:
  t_max: 4000000
logging:
  use_wandb: True
  project_name: "Pogema-16x16-PyMARL"
env_args:
  grid_config:
    map_name: 
      grid_search: [Easy16x16, Normal16x16, Hard16x16, ExtraHard16x16]
