algo: QMIX
#  grid_search: [ QMIX, VDN, IQL, ]
settings:
  t_max: 2000000
logging:
  use_wandb: True
  project_name: "Pogema-16x16"
env_args:
  name:
    grid_search:
      - "Pogema-16x16-extra-hard-v0"
      - "Pogema-16x16-hard-v0"
      - "Pogema-16x16-normal-v0"
      - "Pogema-16x16-easy-v0"
