algo: 
  grid_search: [ QMIX, VDN, IQL, ]
settings:
  t_max: 8000000
logging:
  use_wandb: True
  project_name: "Pogema-32x32-PyMARL"
env_args:
  grid_config:
    map_name: 
      grid_search: [Easy32x32, Normal32x32, Hard32x32, ExtraHard32x32]
