algo: 
  grid_search: [ QMIX, VDN, IQL, ]
settings:
  t_max: 2000000
logging:
  use_wandb: True
  project_name: "Pogema-8x8-PyMARL"
env_args:
  grid_config:
    map_name:
      grid_search: [Easy8x8, Normal8x8, Hard8x8, ExtraHard8x8]
