name: pogema-sf

global_settings:
  use_wandb: True 
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 100000000
async_ppo:
  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 2048
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 8
  num_envs_per_worker: 8
environment:
  name: Pogema-v0 
  grid_config: 
    num_agents: 32
    size: 32
    max_episode_steps: 128
    density: 0.3
    obs_radius: 5
